### ISSUE TITLE
fapp does not generate run() function call with proper syntax

### ISSUE THREAD

**Issue by qhuydtvt** [jleonra/flask-snippets#3]
Generate code:

`if __name__ == '__main__':
  app.run(host:'127.0.0.1', port=8000, debug=True)`

Errors:

https://www.dropbox.com/s/4zgrvbdum5wghiv/Screenshot%202017-10-12%2016.23.18.png?dl=0

Expected code:

`if __name__ == '__main__':
  app.run(host**=**'127.0.0.1', port=8000, debug=True)`

**Comment by m1waterman88** [comment]
I found this and will be forking to fix it and any other maintenance needed, as it appears the repo has been abandoned.

**Comment by m1waterman88** [comment]
It seems this repository is no longer maintained. I forked it and amended this issue, and I made some other changes. Planning to maintain and add features. You can download it in Atom by searching [flask-snips](https://github.com/m1waterman88/flask-snips).

**Comment by qhuydtvt** [comment]
Thank you very much
